import { Goal, UserProfile, WeeklyReview, ChatMessage } from "@/types";

export const initialUserProfile: UserProfile = {
  name: "Dhruva",
  email: "dhruva@example.com",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  streakDays: 7,
  totalXp: 850,
  level: 7,
  joinedDate: "2026-08-01",
};

export const initialGoals: Goal[] = [
  {
    id: "goal-dsa-1",
    title: "DSA Preparation for Tech Interviews",
    description: "Master Data Structures & Algorithms, solve 150+ LeetCode problems, and develop strong algorithmic problem solving skills.",
    targetDeadline: "2026-11-30",
    currentLevel: "beginner",
    dailyMinutesTarget: 90,
    preferredSchedule: "evening",
    status: "active",
    createdAt: "2026-08-10",
    category: "coding",
    weakAreas: ["Recursion", "Two Pointers with Edge Cases", "Dynamic Programming memoization"],
    strongAreas: ["Arrays Basics", "Prefix Sums", "Hash Maps"],
    milestones: [
      {
        id: "ms-1",
        goalId: "goal-dsa-1",
        title: "Arrays, Strings & Two Pointers",
        description: "Core linear structures, sliding window, and two pointer patterns.",
        order: 1,
        status: "in_progress",
        estimatedDays: 14,
        tasks: [
          {
            id: "task-101",
            milestoneId: "ms-1",
            title: "Arrays Revision & Kadane's Algorithm",
            description: "Review maximum subarray sum and time complexity trade-offs.",
            difficulty: "easy",
            estimatedMinutes: 30,
            dueDate: "2026-09-17",
            status: "completed",
            priority: "high",
            topic: "Arrays",
            tags: ["theory", "revision"],
          },
          {
            id: "task-102",
            milestoneId: "ms-1",
            title: "Solve 3 Two-Pointer Practice Problems",
            description: "Target: Container With Most Water, 3Sum Closest, and Valid Palindrome II.",
            difficulty: "medium",
            estimatedMinutes: 45,
            dueDate: "2026-09-17",
            status: "in_progress",
            priority: "high",
            topic: "Two Pointers",
            tags: ["practice", "problem-solving"],
            wasAdapted: true,
            adaptationReason: "Adapted: yesterday you reported difficulty with Two Pointers boundary conditions. Added 1 reinforcement problem.",
          },
          {
            id: "task-103",
            milestoneId: "ms-1",
            title: "Review Mistakes & Document Intuition",
            description: "Write down 2 key takeaways from two-pointer edge cases in study notes.",
            difficulty: "easy",
            estimatedMinutes: 15,
            dueDate: "2026-09-17",
            status: "pending",
            priority: "medium",
            topic: "Reflection",
            tags: ["notes", "review"],
          },
          {
            id: "task-104",
            milestoneId: "ms-1",
            title: "Sliding Window Maximum & Minimum Window Substring",
            description: "Deep dive into variable size window templates with hash map frequency tracking.",
            difficulty: "hard",
            estimatedMinutes: 60,
            dueDate: "2026-09-18",
            status: "pending",
            priority: "high",
            topic: "Sliding Window",
            tags: ["advanced", "problem-solving"],
          },
        ],
      },
      {
        id: "ms-2",
        goalId: "goal-dsa-1",
        title: "Linked Lists & Fast-Slow Pointer",
        description: "Reversals, cycle detection, merge sort on lists, LRU Cache basics.",
        order: 2,
        status: "locked",
        estimatedDays: 10,
        tasks: [
          {
            id: "task-201",
            milestoneId: "ms-2",
            title: "Reverse Linked List (Iterative & Recursive)",
            description: "Understand 3 pointer state transitions.",
            difficulty: "easy",
            estimatedMinutes: 45,
            dueDate: "2026-09-22",
            status: "pending",
            priority: "high",
            topic: "Linked List",
          },
          {
            id: "task-202",
            milestoneId: "ms-2",
            title: "Floyd's Cycle Detection & Cycle Entry Point",
            description: "Mathematical proof and implementation.",
            difficulty: "medium",
            estimatedMinutes: 45,
            dueDate: "2026-09-23",
            status: "pending",
            priority: "medium",
            topic: "Linked List",
          },
        ],
      },
      {
        id: "ms-3",
        goalId: "goal-dsa-1",
        title: "Stacks, Queues & Monotonic Pattern",
        description: "Next greater element, histogram largest rectangle, and BFS queues.",
        order: 3,
        status: "locked",
        estimatedDays: 12,
        tasks: [],
      },
      {
        id: "ms-4",
        goalId: "goal-dsa-1",
        title: "Binary Trees & BST Traversals",
        description: "DFS pre/in/post order, BFS level order, height and diameter calculations.",
        order: 4,
        status: "locked",
        estimatedDays: 15,
        tasks: [],
      },
      {
        id: "ms-5",
        goalId: "goal-dsa-1",
        title: "Graphs & Dynamic Programming",
        description: "Graph traversals (BFS/DFS, Dijkstra), 1D & 2D DP memoization and tabulation.",
        order: 5,
        status: "locked",
        estimatedDays: 20,
        tasks: [],
      },
    ],
  },
  {
    id: "goal-japanese-2",
    title: "Japanese JLPT N3 Certification",
    description: "Master 650 Kanji, 3,750 vocabulary words, and conversational grammar patterns.",
    targetDeadline: "2027-03-31",
    currentLevel: "intermediate",
    dailyMinutesTarget: 45,
    preferredSchedule: "morning",
    status: "active",
    createdAt: "2026-07-15",
    category: "language",
    weakAreas: ["Passive-Causative Verb Conjugation", "Speed Reading Kanji"],
    strongAreas: ["Hiragana/Katakana", "N4 Vocabulary", "Listening comprehension"],
    milestones: [
      {
        id: "ms-j1",
        goalId: "goal-japanese-2",
        title: "N3 Kanji Mastery (First 200)",
        description: "Onyomi, Kunyomi, and compound words with Anki SRS.",
        order: 1,
        status: "in_progress",
        estimatedDays: 30,
        tasks: [
          {
            id: "task-j101",
            milestoneId: "ms-j1",
            title: "Anki Kanji Review (25 cards)",
            description: "Practice stroke order and sentence readings.",
            difficulty: "easy",
            estimatedMinutes: 20,
            dueDate: "2026-09-17",
            status: "completed",
            priority: "high",
            topic: "Kanji",
          },
          {
            id: "task-j102",
            milestoneId: "ms-j1",
            title: "Grammar Bunpro N3 Lesson 4",
            description: "Learn ~わけにはいかない and ~ざるを得ない usage.",
            difficulty: "medium",
            estimatedMinutes: 25,
            dueDate: "2026-09-17",
            status: "pending",
            priority: "medium",
            topic: "Grammar",
          },
        ],
      },
    ],
  },
  {
    id: "goal-portfolio-3",
    title: "Build Production Full-Stack AI Portfolio",
    description: "Ship an end-to-end full stack application with Next.js, FastAPI, Vector DB, and live deployment.",
    targetDeadline: "2026-10-31",
    currentLevel: "intermediate",
    dailyMinutesTarget: 60,
    preferredSchedule: "evening",
    status: "active",
    createdAt: "2026-09-01",
    category: "career",
    weakAreas: ["Docker deployment configs", "Vector indexing tuning"],
    strongAreas: ["React UI/UX", "REST APIs", "Tailwind CSS"],
    milestones: [
      {
        id: "ms-p1",
        goalId: "goal-portfolio-3",
        title: "Architecture & Backend API Design",
        description: "Database schemas, auth pipelines, and core agent orchestration.",
        order: 1,
        status: "in_progress",
        estimatedDays: 14,
        tasks: [
          {
            id: "task-p101",
            milestoneId: "ms-p1",
            title: "Design PostgreSQL schema on Supabase",
            description: "Define relations for users, goals, milestones, tasks, and check-ins.",
            difficulty: "medium",
            estimatedMinutes: 45,
            dueDate: "2026-09-17",
            status: "completed",
            priority: "high",
            topic: "Database",
          },
        ],
      },
    ],
  },
];

export const initialWeeklyReview: WeeklyReview = {
  id: "review-week-37",
  goalId: "goal-dsa-1",
  weekStartDate: "2026-09-08",
  weekEndDate: "2026-09-15",
  tasksCompleted: 18,
  tasksTotal: 22,
  completionRatePercent: 82,
  consistencyScorePercent: 88,
  totalHoursSpent: 12.5,
  strongAreas: ["Arrays", "Prefix Sums", "Two Pointer basics"],
  weakAreas: ["Recursion Base Cases", "Binary Search Lower Bound edge cases"],
  keyWins: [
    "Maintained a 7-day continuous study streak",
    "Solved Kadane's Algorithm in under 15 minutes",
    "Completed 82% of assigned high-priority tasks",
  ],
  nextWeekFocus: [
    "Reduce passive video theory time from 35% to 15%",
    "Increase active problem solving with 5 dedicated recursion drills",
    "Adapt daily study target on weekdays to 75m to prevent burnout",
  ],
  aiExecutiveSummary:
    "You demonstrated great consistency this week! Your speed and confidence in Array manipulation is now solid. However, our check-in data shows high perceived difficulty when branching into recursive sub-problems. Next week's adaptive roadmap will scaffold recursion gradually before tackling trees.",
};

export const initialCoachMessages: ChatMessage[] = [
  {
    id: "msg-1",
    sender: "coach",
    content: "Good evening Dhruva! 🚀 You have a 7-day streak going strong. Today's focus is on Two-Pointer problems. Yesterday you mentioned feeling slightly stuck on boundary conditions, so I've customized today's 3 problems specifically around sorted pointer movement.",
    timestamp: "6:00 PM",
    suggestedActions: [
      { label: "Start Today's Tasks", action: "start_tasks" },
      { label: "I only have 30 mins today", action: "quick_time" },
      { label: "Explain Two-Pointers visually", action: "explain_concept" },
    ],
    contextTag: "DSA Preparation • Milestone 1",
  },
];
